baseURL = "https://log101.github.io"
languageCode = "tr"
defaultContentLanguage = "tr"
title = "log101"
theme = "hermit"
# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10  # Maximum number of items in the RSS feed.
enableEmoji = true
paginate = 5

[languages]
  [languages.tr]
    disabled = false
    languageCode = 'tr'
    languageDirection = 'ltr'
    languageName = 'Türkçe'
    title = 'Log101'
    weight = 10

  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Log101'
    weight = 20

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "log101'in sayfası"
  themeColor = "#494f5c"

  homeSubtitle = ""

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields

  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  [params.author]
    name = "Furkan Erdem"

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "github"
    url = "https://github.com/"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/furkan-erdem-506548218"

[menu]

  [[menu.main]]
    identifier = 'posts'
    name = "Yazılar"
    url = "posts/"
    weight = 10

  [[menu.main]]
    identifier = 'projects'
    name = "Projeler"
    url = "about/"
    weight = 20

  [[menu.main]]
    name = "Github"
    url = "about/"
    weight = 30

  [[menu.main]]
    name = "CV"
    url = "about/"
    weight = 40

  [[menu.main]]
    identifier = 'stories'
    name = "Hikayeler"
    url = "about/"
    weight = 50

  [[menu.main]]
    identifier = 'running'
    name = "Koşu"
    url = "about/"
    weight = 60
