baseURL = "https://log101.github.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "log101"
theme = "hermit"
# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true

rssLimit = 10  # Maximum number of items in the RSS feed.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/

[author]
  name = "Furkan Erdem"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "log101's blog"
  themeColor = "#494f5c"

  homeSubtitle = "\"Orada, soğuk ve mütemadiyen dönen yaşlı başlı yıldızlar, önce israillenmiş sonra pislik içinde bırakılmış gezegenler, Kadimler mirası kuyruklu gök cisimleri vardı; birbirlerinden bağımız görünseler de modellenmesi neredeyse imkansız bir örgü içerisinde…\""

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields

  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "github"
    url = "https://github.com/"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/furkan-erdem-506548218"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about-hugo/"
    weight = 20
